# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-23 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='presentFinancialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_name', models.CharField(max_length=50)),
                ('assets_valuation', models.FloatField()),
                ('liabilities_name', models.CharField(max_length=50)),
                ('liabilities_valuation', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetsmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='assetsModel',
        ),
    ]
