# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20210224_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentfinancialmodel',
            name='liabilities_name',
            field=models.CharField(default='asdf', max_length=50),
        ),
        migrations.AddField(
            model_name='presentfinancialmodel',
            name='liabilities_valuation',
            field=models.FloatField(default=123),
        ),
        migrations.AlterField(
            model_name='presentfinancialmodel',
            name='assets_name',
            field=models.CharField(blank=True, default='asdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='presentfinancialmodel',
            name='assets_valuation',
            field=models.FloatField(blank=True, default=123),
        ),
    ]
