# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-24 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0007_auto_20210224_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='presentAssetsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_name', models.CharField(blank=True, default='', max_length=50)),
                ('assets_valuation', models.FloatField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='presentLiabilitiesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liabilities_name', models.CharField(blank=True, default='', max_length=50)),
                ('liabilities_valuation', models.FloatField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='presentfinancialmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='presentFinancialModel',
        ),
    ]
