# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_addinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserexpense',
            name='expense_repeat_frequency',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adduserexpense',
            name='expense_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adduserexpense',
            name='expense_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='adduserexpense',
            name='expense_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
