# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-01 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0013_auto_20210226_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='addUserInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(default='', max_length=50)),
                ('investment_date', models.DateField(default='')),
                ('investment_amount', models.PositiveIntegerField(default=0)),
                ('investment_repeat_frequency', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='addinvestment',
            name='user',
        ),
        migrations.DeleteModel(
            name='addInvestment',
        ),
    ]
