# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-26 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0014_auto_20210301_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='allPredictionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.PositiveIntegerField()),
                ('monthly_expense', models.PositiveIntegerField()),
                ('yearly_expense', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('dependents', models.PositiveIntegerField()),
                ('investmentTotal', models.PositiveIntegerField()),
                ('investmentMonthly', models.PositiveIntegerField()),
                ('healthInsurance', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
