# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_allpredictionsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserexpense',
            name='expense_duration_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adduserinvestment',
            name='investment_duration_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
