# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_auto_20210513_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpredictionsdata',
            name='highLiquid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='dependents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='healthInsurance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='investmentMonthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='investmentTotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='monthly_expense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='monthly_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allpredictionsdata',
            name='yearly_expense',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
