# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-31 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_auto_20210530_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpredictionsdata',
            name='healthInsurancePremium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
