# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdivision',
            name='liquidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentdivision',
            name='risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentdivision',
            name='investmentPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentdivision',
            name='investmentType',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
